microsoft/botbuilder-tools

- QnAMaker/bin/qnamaker
- QnAMaker/package.json
Removing the requirement to have KB ID always specified (you don't need this when you are trying to create a new KB). 
Also fixing the package.json for this package to be "QnAMaker"
> Fixing package name, removing req to have KBID

- README.md
- Updated LUISGen badge to point to [LUISGen](https://badge.fury.io/js/luisgen), not botdispatch.
N/A
> Fix LUISGen badge

- Ludown/lib/parseFileContents.js
str.search used a regexp and any special characters such as $, [, (, ], ), ^ will create problems. Since we are doing a replace above and then looking for indexOf for the replace text, this should be good. All tests pass.
Fixes #198 
Using str.indexOf instead of str.search as str.search assumes regexp matching.
```
> # Intent definitions
- test funky {EntityOne=$symbol} in entity
- test funky {EntityOne=[symbol]} in entity
- test funky {EntityOne=this$ is a [weird] entity} but oh well
- another {EntityOne=te$st}
- another {EntityOne=te&st}
> # Entity definitions
$EntityOne:simple
$EntityTwo:simple
> # PREBUILT Entity definitions
> # Phrase list definitions
> # List entities
```
```
{
"intents": [
{
"name": "None"
},
{
"name": "TestIntent"
}
],
"entities": [
{
"name": "EntityOne",
"roles": …
```
> using str.indexOf to avoid issues when entity text includes regexp control characters

- MSBot/README.md
Fixes #222 
Documentation change. Fixes gaps/changes in the documentation mentioned in #222, so that the README information more closely aligns with the `-h` output of each service connection command, including parameters previously missing in the README tables.
> README changes to align parameter tables with help output

- QnAMaker/examples/ReplaceKbDTO.json
- QnAMaker/lib/api/dataModels/replaceKbDto.js
- QnAMaker/lib/help.js
- QnAMaker/package-lock.json
- QnAMaker/package.json
Fixes #227 
1. Fixed the issue
2. Added an example qna replace document so this shows up with qnamaker replace kb -h
3. Updated the root help table so replace command shows up under qnamaker -h
> Fixes to get QnAMaker replace command working

- Chatdown/lib/index.js
While trying to consume Chatdown as a library in the emulator, I ran into an issue where calling
`chatdown(chatFileContents)` was throwing an error because I wasn't passing in an empty `args` object
- added a default value to `args` parameter in `readContents()` function
- this will prevent the function from throwing an undefined reference error when it checks `args.in` when an args object is omitted from the call
> [Chatdown] Added default value to arg in readContents()

- .gitignore
- Chatdown/lib/index.js
- Chatdown/package-lock.json
- Chatdown/package.json
- Chatdown/readme.md
- Chatdown/test/chatdown.cli.test.suite.js
- handle macOS/*nix linefeeds
- update commandline tests
- fix readme
- ignore macOS specific files
Fixes # issue 252
macOS and *nix linefeeds are different than windows.  this fix addresses those differences and also updates the command line tests.  library tests are not addressed in this pull.
no new tests added, but updates to the cli tests were made and are included in this PR
> macOS commandline fixes

- MSBot/docs/readme.md
I updated the README in the MSBot root folder a week or so back to replace localhost with endpoint, and add the appropriate command line switches per service. With this commit, I'm reflecting those changes in the README that is in the "docs" folder. Not sure if this file should be removed altogether though since it is duplicate content.
> Edited to reflect previous changes to the README in the MSBot root

- .eslintignore
- Ignore MSBot/* files from ESLint since it is entirely based in TS files
> Ignore MSBot from ESLint

- Dispatch/readme.md
Fixes #
- Removed keys from documentation (e.g. LUIS app ID, QnA KB ID, etc.)
- used x's as placeholders so readers can still understand they 1.) need their own key and 2.) are grabbing right key by following at least the pattern (e.g. LUIS App ID has pattern xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
> removed keys from docs

- Chatdown/test/mocha.opts
- LUIS/test/mocha.opts
- QnAMaker/test/mocha.opts
Related to #292 
Randomly but often, CLI tools tests fail when for the --help switch (which should output the help message in the stdout). This is usually the first tets of the suite (for QnA, LUIS and Chatdown tools).
- Temporarily increase the mocha.opts timeout setting from 10000 to 3000
- Keep the original issue open since this is not a proper solution to the problem
- Remove the timeout option in mocha.opts since unit tests should run flawlessly with defaults
This happens mainly in Travis, locally is not that common. We should keep an eye on the Travis builds.
> [Travis] Temporarily increase test timeout

- package-lock.json
- package.json
Fixes build
- Add dotnet-2.0.0 as devDependency in root's package.json
- This solves a race condition issue when installing the same dependency for LUISGen and Dispatch tools
Travis build process should pass without errors
> Fix travis build adding dotnet-2.0.0 as root devDependency

- packages/MSBot/src/msbot-clone.ts
- packages/MSBot/src/msbot-connect-azure.ts
- packages/MSBot/src/msbot-connect-dispatch.ts
- packages/MSBot/src/msbot-connect-endpoint.ts
- packages/MSBot/src/msbot-connect-luis.ts
- packages/MSBot/src/msbot-connect-qna.ts
- packages/MSBot/src/msbot-export.ts
- packages/MSBot/src/msbot-list.ts
- Replaced empty brackets with `undefined` in order to fix the 'no-empty' warnings from TSLint in MSBot.
> Fixed TSLint 'no-empty' warnings in MSBot

- packages/MSBot/src/BotConfig.ts
- packages/MSBot/src/models/botConfigModel.ts
- Double blank lines in two different files were reduced to only one for fixing 'no-consecutive-blank-lines'.
- Two `for` structures were replaced with `for-of` structures as suggested by TSLint for fixing 'prefer-for-of' warnings in MSBot.
> Fixed TSLint 'prefer-for-of' and 'no-consecutive-blank-lines' in MSBot

- packages/MSBot/src/msbot-clone.ts
- packages/MSBot/src/msbot-connect-azure.ts
- packages/MSBot/src/msbot-connect-dispatch.ts
- packages/MSBot/src/msbot-connect-endpoint.ts
- packages/MSBot/src/msbot-connect-file.ts
- packages/MSBot/src/msbot-connect-luis.ts
- packages/MSBot/src/msbot-connect-qna.ts
- packages/MSBot/src/msbot-connect.ts
- packages/MSBot/src/msbot-disconnect.ts
- packages/MSBot/src/msbot-export.ts
- packages/MSBot/src/msbot-init.ts
- packages/MSBot/src/msbot-list.ts
- packages/MSBot/src/msbot-secret.ts
- packages/MSBot/src/msbot.ts
- The 'no-console' rule was disabled in some files located in MSBot\src\. These files correspond to a console functionality , so the commands console.error are needed.
> Fixed 'no-console' TSLint warnings.

- packages/MSBot/src/models/botConfigModel.ts
- packages/MSBot/src/models/qnaMakerService.ts
- packages/MSBot/src/msbot-secret.ts
- Modified declarations when const was preferred instead of let as suggested by TSLint.
> Fixed TSLint 'prefer-const' warnings in MSBot

- packages/MSBot/src/BotConfig.ts
- packages/MSBot/src/msbot-init.ts
- Removed an extra semi colon in a file.
- Removed concatenating in a `string`, instead used `string template`.
> Fixed TSLint 'prefer-template' and 'type-literal-delimiter' warnings in MSBot

- packages/MSBot/src/msbot-connect.ts
Fix the following warnings in the file `msbot-connect.ts`:
- `typedef`
- `no-any`
> Fix TSLint warnings in msbot-connect.ts

- packages/MSBot/src/msbot-export.ts
Fix the following warnings in the file `msbot-export.ts`:
- `typedef`
- `no-any`
> Fix TSLint warnings in msbot-export.ts

- packages/MSBot/src/msbot-clone.ts
Fix the following warnings in the file `msbot-clone.ts`:
- `typedef`
- `no-any`
> Fix TSLint warnings in msbot-clone.ts

- packages/MSBot/src/msbot-init.ts
Fix the following warnings in the file `msbot-init.ts`:
- `typedef`
- `no-any`
- `curly`
- `one-line`
- `prefer-template`
> Fix TSLint warnings in msbot-init.ts

- packages/MSBot/src/msbot-list.ts
Fix the following warnings in the file `msbot-list.ts`:
- `typedef`
- `no-any`
- `no-empty`
- `no-consecutive-blank-lines`
- `one-line`
> Fix TSLint warnings in msbot-list.ts

- packages/MSBot/src/msbot-secret.ts
Fix the following warnings in the file`msbot-secret.ts`:
- `typedef`
- `no-any`
- `eofline`
> Fix TSLint warnings in msbot-secret.ts

- packages/MSBot/src/msbot-connect-qna.ts
Fix the following warnings in the file `msbot-connect-qna.ts`:
- `typedef`
- `no-any`
- `no-empty`
- `one-line`
- `curly`
- `eofline`
> Fix TSLint warnings in msbot-connect-qna.ts

- packages/MSBot/src/msbot-get.ts
Fix the following warnings in the file `msbot-get.ts`:
- `typedef`
- `no-any`
- `no-empty`
- `no-consecutive-blank-lines`
- `no-var-keyword`
- `one-line`
- `eofline`
> Fix TSLint warnings in msbot-get.ts

- packages/LUIS/bin/luis
Fixes #408
- Replace `break` with `return` after outputting json result.
- Add comment `// Write output to console and return` on each occurrence
```
$str = luis import application --in "" --appName "" --authoringKey "" --endpointBasePath ""
$json = "$str".Substring(0, "$str".Length / 2) | ConvertFrom-Json
```
> Fix #408: duplicated json output on import app

- packages/MSBot/src/msbot-disconnect.ts
Fix the following warnings in the file `msbot-disconnect.ts`:
- `typedef`
- `no-any`
- `no-consecutive-blank-lines`
- `eofline`
> Fix TSLint warnings in msbot-disconnect.ts

- packages/MSBot/src/msbot-connect-endpoint.ts
Fix the following warnings in the file `msbot-connect-endpoint.ts`:
- `typedef`
- `no-any`
- `no-trailing-whitespace`
- `no-empty`
- `one-line`
- `curly`
- `no-object-literal-type-assertion`
- `space-within-parens`
- `eofline`
> Fix TSLint warnings in msbot-connect-endpoint.ts

- packages/MSBot/src/msbot-connect-luis.ts
Fix the following warnings in the file `msbot-connect-luis.ts`:
- `typedef`
- `no-any`
- `no-empty`
- `one-line`
- `curly`
- `quotemark`
- `eofline`
> Fix TSLint warnings in msbot-connect-luis.ts

- packages/MSBot/src/msbot-connect-blob.ts
The following TSLint issues have been fixed:
- `typedef`
- `no-any`
- `quotemark`
- `no-empty`
- `one-line`
- `curly`
- `eofline`
A key had to be added to `IConnectGenericArgs` to be able to iterate through its properties. The type of the key had to be `any` to avoid conflict with `for (const key of args.keys)`. An exception for `no-any` has been added to that particular line.
> Fix TSLint warnings in msbot-connect-blob.ts

- packages/MSBot/src/msbot-connect-generic.ts
The following TSLint issues have been fixed in `msbot-generic.ts`
- typedef
- no-any
- interface-name
- curly
- prefer-const
- no-var-keyword
- forin
- newline-before-return
- eofline
A key had to be added to `IConnectGenericArgs` to be able to iterate through its properties.
> Fix TSLint warnings in msbot-generic.ts

- packages/MSBot/src/msbot-connect-dispatch.ts
Fix the following warnings in the file `msbot-connect-dispatch.ts`:
- `typedef`
- `no-any`
- `quotemark`
- `no-empty`
- `one-line`
- `curly`
- `switch-default`
- `switch-final-break`
- `whitespace`
- `eofline`
> Fix TSLint warnings in msbot-connect-dispatch

- packages/MSBot/package-lock.json
- packages/MSBot/package.json
- packages/MSBot/src/msbot.ts
The following rules have been fixed:
- typedef
- no-require-imports
- no-var-requires
- no-any
To fix `no-var-require`, a dependecy for `semver` was added in package.json.
To fix `no-any` for const `pkg`, a new interface was added.
The variable `a` was renamed to `unknownArgs`.
> Fix TSLint warnings in msbot.ts

- packages/MSBot/src/msbot-init.ts
- Replace the casting of `program.Command` to type `<any>` with `Object.assign()`.
- This also fixes a previous method using a property assignation loop
The changes were tested using `msbot-init.ts`.
> Proposed fix to `no-any` TSLint` rule  when parsing commands using `Object.assign()`

- packages/LUIS/package.json
packages.config added explicit list of files to include and pattern didn't include .json file which drives entire command line help system.
Fix: I include the critical file. :)
> include operation.json in package

- tslint.json
Add configuration in the `tslint.json` to exclude the path `"packages/LUIS/src/**"` from the TSLint check as this path only contains autogenerated code.
TSLint shouldn't detect any warning in files located in this path.
> Exclude LUIS from TSLint check

- packages/MSBot/src/msbot-connect-appinsights.ts
- packages/MSBot/src/msbot-connect-blob.ts
- packages/MSBot/src/msbot-connect-bot.ts
- packages/MSBot/src/msbot-connect-cosmosdb.ts
- packages/MSBot/src/msbot-connect-dispatch.ts
- packages/MSBot/src/msbot-connect-endpoint.ts
- packages/MSBot/src/msbot-connect-file.ts
- packages/MSBot/src/msbot-connect-generic.ts
- packages/MSBot/src/msbot-connect-luis.ts
- packages/MSBot/src/msbot-connect-qna.ts
Fix the following TSlint warnings:
- typedef
- align
- curly
Travis will no longer report these warnings
> Fixed TSLint warnings in msbot-connect-*.ts files

- build.ci.sh
- package.json
- To make easier running code coverage locally we extracted the `coverage` script.
- To keep Coveralls integration we created `coveralls` script reusing `coverage`.
- Updated `build.ci.sh` to run `coveralls`
To run code coverage locally:
```
npm install
npm run build
npm run coverage
```
> [Build] Split `coverage` and `coveralls` scripts

- packages/MSBot/src/msbot-disconnect.ts
- packages/MSBot/src/msbot-export.ts
- packages/MSBot/src/msbot-get.ts
- packages/MSBot/src/msbot-init.ts
- packages/MSBot/src/msbot-list.ts
- packages/MSBot/src/msbot-secret.ts
- packages/MSBot/src/msbot.ts
- Disable TSLint rule for no-object-literal-type-assertion
Travis should no longer report this warning
> Disable TSLint rule for no-object-literal-type-assertion

- packages/MSBot/src/msbot-connect-appinsights.ts
- packages/MSBot/src/msbot-connect-blob.ts
- packages/MSBot/src/msbot-connect-bot.ts
- packages/MSBot/src/msbot-connect-cosmosdb.ts
- packages/MSBot/src/msbot-connect-dispatch.ts
- packages/MSBot/src/msbot-connect-endpoint.ts
- packages/MSBot/src/msbot-connect-file.ts
- packages/MSBot/src/msbot-connect-generic.ts
- packages/MSBot/src/msbot-connect-luis.ts
- packages/MSBot/src/msbot-connect-qna.ts
- Disable TSLint rule for no-object-literal-type-assertion
Travis should no longer report this warning
> Disable TSLint rule for no-object-literal-type-assertion in msbot-connect*.ts files

- packages/Chatdown/.vscode/launch.json
- packages/Chatdown/lib/index.js
- packages/Chatdown/test/chatdown.lib.test.suite.js
When there was no text then suggestedActions check for content was incorrect.
Fixes #470 
correctly check length of actions array.
> check for suggestedActions length incorrect

- packages/MSBot/src/msbot-clone-services.ts
- packages/MSBot/src/msbot-connect-blob.ts
- packages/MSBot/src/msbot-connect-qna.ts
- packages/MSBot/src/msbot-export-services.ts
- packages/MSBot/src/msbot-update-qna.ts
--verbose doesn't work from cli, but does from debugger due to regression introduced by southworks.
> fix regression in verbose

- packages/Dispatch/bin/dispatch.js
so it won't depend on .NET Core 2.1 being installed globally
Fixes #
- 
-
-
> updated dispatch.js 

- packages/MSBot/src/msbot-clone-services.ts
fixes #586
msbot clone was looking for BotSecret instead of botFileSecret.  
Code now pulls botFileSecret and if not there will generate a key and set the botFileSecret setting.
> change bot secret to botFileSecret

- packages/MSBot/src/msbot-clone-services.ts
Fixes #596 
Add appId and appSecret parameters to msbot clone services which is then passed into az bot create. This provides a workaround to the auto-provision of applicationIds/Secrets being experienced by customers
> Workaround for auto-provision failure of ApplicationId

- README.md
LUISGen and LUIS require .net core.  so added this to the pre-reqs section of the readme
> Add .net core to pre-reqs

- packages/Ludown/test/verified/zh-Hans/reduced.lu
Translation service started returning a slightly modified text for zh-CN. This change updates the impacted ludown tests so the expected translated content matches what's returned by the service call.
> Fix for ludown translate test

- packages/MSBot/src/msbot-clone-services.ts
Fixes #https://github.com/Microsoft/botbuilder-tools/issues/667
Add --noDecorate switch so bot.config files don't get pre-pended with the bot name.
@tomlm/@stevengum Need some help here.
> [DO NOT MERGE] Add --noDecorate so LUIS/Dispatch names don't get prepended

- packages/LUIS/bin/luis.js
- packages/Ludown/lib/helpers.js
- packages/Ludown/lib/ludown-parse-ToLuis.js
- packages/Ludown/lib/ludown-parse-ToQna.js
- packages/Ludown/lib/ludown-parse.js
- packages/Ludown/lib/ludown-refresh.js
- packages/Ludown/lib/ludown-translate.js
- packages/Ludown/lib/ludown.js
- packages/Ludown/lib/parseFileContents.js
- packages/Ludown/lib/parser.js
- packages/Ludown/lib/toLU-helpers.js
- packages/Ludown/lib/toLU.js
- packages/Ludown/lib/translate-helpers.js
- packages/Ludown/lib/translate.js
- packages/Ludown/lib/utils.js
- Remove unused `const` for `intercept-stdout` in LUIS and Ludown files.
- Move validation for `--prefix` argument before the validation for `--help`, otherwise it will not intercept output for the `--help` output text.
Calling `luis --help --prefix` will append the prefix to the output of the command.
The removal of the unused `const` will not modify the behavior of the code.
> Remove const for intercept-stdout for LUIS y Ludown, Fix --help with no prefix in LUIS

- packages/LUISGen/src/npm/package.json
- packages/LUISGen/src/npm/readme.md
readme had erroneous spaces at beginning of line causing markdown to not render correctly
bump version of package
> bump version and remove spaces at start of line in readme

- packages/QnAMaker/bin/qnamaker.js
- packages/QnAMaker/package-lock.json
- packages/QnAMaker/package.json
- packages/QnAMaker/test/qnamaker.cli.test.suite.js
Add `--prefix` arg to enable prefix in messages in `QnAMaker`.
Three new tests were added to validate the correct use of the prefix.
> Add --prefix arg to enable prefix in QnA

- packages/MSBot/docs/bot-file-encryption.md
I would consider either using single `:` after **NOTE** or **WARNING** or not using at all. 
If this PR breaks some rules in codebase for botbuilder-tools, let me know, I don't know them. I am consumer of BOT-related stuff.
> MSBot docs - "::" vs. ""(empty)

- packages/Chatdown/test/cli.transcript
- packages/Chatdown/test/sample.transcript
- packages/QnAMaker/bin/qnamaker.js
- packages/QnAMaker/package-lock.json
- packages/QnAMaker/package.json
- packages/QnAMaker/test/qnamaker.cli.test.suite.js
> Added proxy support to cli

- packages/Ludown/lib/enums/luisbuiltintypes.js
Adds `geographyV2` and `personName` to the list of supported prebuilt entities.
Fixes #771
I suggest we automatize this process in the future.
> Added prebuilt entities support based on latest locale support for pre-builts from LUIS

- packages/MSBot/docs/add-services.md
1. Delete wrong option "--connectionString"
2. Add cosmosDB Example
```shell
msbot connect cosmosdb -n <COSMOS-DB-NAME> -t <TENANT-ID> -s <SUBSCRIPTION-ID> -r <RESOURCE-GROUP-NAME> --serviceName <COSMOS-DB-NAME> -e <COSMOSDB-ENDPOINT> -d <DB-NAME> -c <COLLECTION-NAME>
```
> Delete wrong option and Add cosmosDB example 

- packages/LUIS/bin/help.js
- packages/LUIS/bin/luis.js
- packages/LUIS/package-lock.json
- packages/LUIS/package.json
Fixes #
The -query command was missing a number of parameters.  Also added the ability to specify an explicit endpoint in order to be able to query containers and the ability to do basic query timings.
> Add missing query parameters and timing.

- packages/MSBot/src/msbot-clone-services.ts
Fixes #831 
- Switched from undocumented --noDecorate to --decorate. By default, bot-name will not be prefixed to LUIS application names. 
- For testing purposes, you can pass in the --decorate option so LUIS application names are prefixed with bot-name. 
Verified that by default, LUIS app names are not prefixed with bot name. 
Verified that cafebot nodejs sample deploys and works E2E with this fix.
> MSBot: Remove bot-name prefix from LUIS applications created via msbot clone services

- packages/LUIS/src/luisAuthoringContext.ts
Sets (or appends) the user-agent for LUIS as follows:
**package-name/package-version (os-platform; node-platform)**
for example on my machine running LUIS I get a full user-agent as follows:
'Node/v10.9.0 (x64-Windows_NT-10.0.17763) ms-rest-js/0.1.0 luis-apis/2.1.0 (x64-Windows_NT-10.0.17763; Node.js,Version=v10.9.0) azure-sdk-for-js'
> user agent for LUIS cli

- packages/MSBot/src/msbot-clone-services.ts
Fixes #
- minor fix to include --verbose to az bot create command if --verbose is set on msbot clone command
- Emulator supports launching a bot file with a specific endpoint configuration loaded. Without this fix, msbot clone will launch emulator to the default 'development' endpoint which results in an incomplete experience for users. With this fix, emulator will be launched to the newly added 'production' endpoint.
Verified that clone works E2E with this change and emulator is launched to open the 'production' endpoint.
> MSBot: Fix Emulator deep link to include the production endpoint id

- packages/MSBot/docs/add-services.md
The region (`-r` and  `--region`) switches were missing from the LUIS connection documentation.
> Region was missing from the table for LUIS

- packages/MSBot/src/msbot-clone-services.ts
Make sure we add a production endpoint and if it's not there don't throw an exception
Fixes
1. Make sure to add production endpoint even if the recipe doesn't have one
2. MAke sure that if there is no production endpoint we don't barf
> Add a production endpoint

- packages/MSBot/package.json
- packages/MSBot/src/msbot-clone-services.ts
Fixes: Unlocks users so that they are able to use the latest AZ CLI with the msbot 4.3.2 (not released yet)
- Bump the version of `msbot` to 4.3.2.
- Changes min AZ CLI requirements
- Change botservice version requirement to use the version released with the core AZ CLI
Used `msbot clone` to deploy a bot.
> msbot: change the az cli requirements

- packages/MSBot/src/msbot.ts
- Rolls back out `msbot --version` change as `--version` is a parameter for connecting LUIS and Dispatch services to bot files. (`msbot --Version` was changed to `msbot --version` in #878)
> msbot: revert `msbot --version`

- packages/Ludown/test/ludown.parsetranslate.test.suite.js
LuDown uses a key which appears to have just expired.  This will temporarily disable these tests until we can refresh the key.
> LuDown Disable test: Key is expired, disable dependent tests.

- packages/Ludown/test/ludown.cli.test.suite.js
- packages/Ludown/test/ludown.translate.test.suite.js
Unblocks #904  
- Solves logical error in ludown refresh command tests
- Disables translate commands unit tests that call the Microsoft Translate Api. Will be replaced with new unit tests in a separate PR.
> Fixing ludown unit tests

- tools-overview.md
Suggested changes to the tools-overview readme:
* Remove the "install bot extension" line since it is no longer needed in the updated Azure CLI
* Change the "download" and "publish" links to point to the official docs since they currently point nowhere and can cause some confusion. Alternatively, we could paste all of the commands in here, but since they don't use `msbot` I didn't think that was necessary
> update tools-overview.md for deployment/publishing

- packages/LUISGen/src/LUISGen.csproj
The nupkg for LUISGen has a project URL that results in a 404. Fixing to point to the correct URL
> Fix project URL in LUISGen nupkg

- packages/LUIS/test/luis.cli.specs.suite.js
- packages/LUIS/test/luis.cli.specs.suite/with-add-verb.spec.json
- packages/LUIS/test/luis.cli.specs.suite/with-get-verb.spec.json
- packages/LUIS/test/testRunner.js
Improve code coverage in LUIS CLI
- Added new test runner to run tests cases from spec json files
- Added new mocha test suite to use test runner and feed with spec files
- Added LUIS CLI 'add' verb argument test cases
- [update] Added LUIS CLI 'get' verb argument test cases
Coveralls code coverage for LUIS CLI should raise
> Add test runner and tests for LUIS 'add' & 'get' verb

- packages/Dispatch/readme.md
Fixes #807
It was suggested that the Dispatch readme should include a troubleshooting section in case people run into the "Unable to install/use dotnet framework" issue. This error occurs when trying to run a dispatch command in any Microsoft-hosted agent pool except "Hosted VS2017."
> Add troubleshooting section

- packages/LUISGen/src/CSharp.cs
- packages/LUISGen/tests/LUISGenTest/Contoso_App.cs
Fixes #939 
LuisGen returns a .NET class which needs to be routinely re-generated as the underlying LUIS model changes. In some scenarios, it may be necessary to change or extend the class for custom behaviours, but the problem is that any changes get overwritten when you next generate the class using LuisGen. The standard pattern to address this is using partial classes.
Verified that the generated C# class contains the partial keyword.
> LUISGen - C# generated class partial

- packages/LUIS/bin/luis.js
Fixes #937
- There are multiple APIs that return their results as JSON strings. These APIs responses are then converted to objects with a property `body` that contains the actual response. To fix the issue, we should reference `result.body` instead of the result directly.
> Fix the add app operation

- packages/Ludown/lib/parseFileContents.js
- packages/Ludown/lib/parser.js
- packages/Ludown/test/ludown.examples.test.suite.js
- packages/Ludown/test/testcases/ref10.lu
- packages/Ludown/test/testcases/ref9.lu
Fixes #855
- Ensures that pattern entities are passed/created to the source file from the referenced file along with the patterns,
- Tests that pattern entities are passed/created to the source file.
- Tests that pattern entities are not passed/created if they already had existed in the source file.
> Fixes pattern entities not being created when referencing patterns in LU files

- packages/MSBot/src/msbot-clone-services.ts
Fixes #958 
Fixes Microsoft/BotBuilder-Samples#1187
Per issues linked above, when `msbot clone services...` runs for a QnA bot, it would previously error out at the `qnamaker create kb...` step because after creating the Cognitive Service in Azure, QnAMaker does some additional setup on the backend that doesn't finish fast enough to be ready.
There seems to be a variable amount of time that it takes for the backend to be ready so this script:
1. Creates a 30-second delay between creation of the Cognitive Service and calling `qnamaker create kb...`
2. Retries the `qnamaker create kb...` command up to 3 times, waiting 15, then 45, then 75 seconds before trying again. Maximum wait time, then, would be over 2 minutes, which should never fail.
Working screenshot:
Screenshot showing retries (I …
> Added wait and retry for qnamaker create kb

- packages/MSBot/src/msbot-clone-service-version.ts
- packages/MSBot/src/msbot-clone-services.ts
- packages/MSBot/test/msbot.clone.test.suite.js
Fixes #962
This PR fixes 2 issues with `ServiceVersion` class:
1. That the regex string assumed the version from `az -v` was ending with a closing ")"
2. That the `isOlder()` function returned unexpected results.  
Please see unit tests below.
Before fix:
- version string "1.2.3" would not parse because the regex pattern was `/([0-9]+)\.([0-9]+)\.([0-9]+)\)/` (as  @v-kydela spotted).
- isOlder returned unexpected results  for  {"major":11,"minor":23,"patch":0} compared to {"major":11,"minor":22,"patch":33}. I'd expect 11.22.33 is older than 11.23.0, but previous code did not. 
Please run unit tests in _packages/MSBot/test/msbot.clone.test.suite.js_.
> ServiceVersion parsing and comparison of versions in msbot-clone-service

- packages/MSBot/package.json
- bump version in order to publish az cli version change bug
Fixes #967 
PR #963 actually addresses the version string format change that is breaking msbot clone services version check.  this commit bumps the tools version number
> bump msbot version number to 4.3.3

- packages/Chatdown/package.json
- packages/Dispatch/package.json
- packages/LUIS/package.json
- packages/LUISGen/src/npm/package.json
- packages/Ludown/package.json
- packages/QnAMaker/package.json
Bump all minor versions for CLI tools except for msbot.
FYI @omarsourour, @ahmedaashour the version number for LUISGen is under [LUISGen/src/npm/package.json](https://github.com/Microsoft/botbuilder-tools/blob/master/packages/LUISGen/src/npm/package-lock.json) 😄
> Increment all tools minor version by 1 except MSbot

- packages/MSBot/docs/export-clone.md
- packages/MSBot/src/msbot-clone-services.ts
Fixes #
- This pull request adds an encryption flag to the msbot clone services.
- Adding -e or --encryption to the command enables the bot file encryption.
- If not added the bot file will not be encrypted.
> Adding encryption flag to Msbot clone services

- packages/Ludown/examples/README.MD
- packages/Ludown/lib/ludown.js
- packages/Ludown/test/ludown.cli.test.suite.js
Fixes #1001
- Fixed incorrect doc under examples/readme.md
- Updated code to include better error message when ludown is invoked without any command specified
- Added new CLI test to verify that the tool spits out helpful text when ludown is invoked without any command specified.
> [Ludown] - improved error message when ludown is invoked without any command

- packages/Ludown/docs/lu-file-format.md
Fixes #950 
- Doc update to clarify ':' is not allowed in entity names.
> [Ludown] Doc fix - ':' is not supported in entity name

- packages/Ludown/lib/helpers.js
- packages/Ludown/test/ludown.helpers.test.suite.js
- Add test case for entities containing 'simple' on its name
- Fix check to check if the entity name it's exactly 'simple' 
The [line 179](https://github.com/southworkscom/botbuilder-tools/blob/5dd7f8894ab758f7344504c86f318d164dda6ede/packages/Ludown/lib/helpers.js#L179) is comparing if the entityType **contains** the word 'simple', giving a wrong comparison if the entity name is a compound name like 'simple-test'.
With the fix in place, the test passes correctly
> [ludown] Fix collision with entities that has 'simple' in their names

- packages/LUIS/src/models/mappers.ts
Fixes #
Issue 1051
Even though the serialized name is correct, the change in the model property name causes the request json to be empty.
- 
-
-
> Fix import version with prebuilt domains

- packages/MSBot/package-lock.json
- packages/MSBot/package.json
- packages/MSBot/src/msbot-connect-appinsights.ts
- packages/MSBot/src/msbot-connect-blob.ts
- packages/MSBot/src/msbot-connect-bot.ts
- packages/MSBot/src/msbot-connect-cosmosdb.ts
- packages/MSBot/src/msbot-connect-dispatch.ts
- packages/MSBot/src/msbot-connect-endpoint.ts
- packages/MSBot/src/msbot-connect-luis.ts
- packages/MSBot/src/msbot-connect-qna.ts
- packages/MSBot/src/msbot-update-appinsights.ts
- packages/MSBot/src/msbot-update-blob.ts
- packages/MSBot/src/msbot-update-cosmosdb.ts
- packages/MSBot/src/msbot-update-dispatch.ts
- packages/MSBot/src/msbot-update-endpoint.ts
- packages/MSBot/src/msbot-update-luis.ts
- packages/MSBot/src/msbot-update-qna.ts
- packages/MSBot/src/utils.ts
Fixes #961 
Powershell changes piped strings to always be UTF16 with Byte-order-mark.  We correctly dealt with bom on text files, but not on stdin streams.
Add byte order mark processing to getStdin()
> fix powershell by stripping byte-order-mark

- packages/LUIS/bin/luis.js
Fixes #951
- Fix the force flag used with the delete API. Currently the delete API call fails if the force flag is used
- Update Packages file with the required version of typescript to make the first installation easier for new contributors
> Fixing force flag + Updating required packages

- build/ExtractCompressNuGet.ps1
This will be run in the build instead of build/packer.dll. (Binaries should not be included in the source repository.)
Packer.dll is to be removed in a later pull request after the builds have been switched over to running ExtractCompressNuGet.ps1.
> Add build/ExtractCompressNuGet.ps1

- packages/lubuild/src/index.ts
LUBuild was not calling ludown with right options which would cause it to break when absolute file paths are specified in the input json. This fixes it.
> [LUBuild] Updating ludown parse call with right options

- packages/LUIS/bin/luis.js
Fixes #1080 
* `westeuerope` => `westeurope`
* `australiaest` => `australiaeast`
* Added `virginia` to output of acceptable args
* The code already considers it acceptable, I just added it to the output that notifies the user of acceptable commands
This was the only location with the typo and it was in a string, so will not affect the rest of the code base.
> minor typo fix

- packages/lubuild/src/IBuildArgs.ts
- packages/lubuild/src/help.ts
- packages/lubuild/src/index.ts
- packages/lubuild/typings/lib/IBuildArgs.d.ts
If you aren't using dialog files you should have to deal with them.
- Added config/args setting **dialogs** which if set to true will turn on generating .dialog files for .lu models
> add switch to turn on saving of .dialog files when building lu

- packages/Ludown/lib/parseFileContents.js
- packages/Ludown/test/ludown.compositeEntity.test.suite.js
- packages/Ludown/test/ludown.roleTests.test.suite.js
- Fixes an issue introduced in 1.3.0 of ludown that breaks VA skills.
- Fix for #1129 
In order to support roles, I re-wrote the core parser that broke existing .lu files that had references to ':' and '=' outside of role definition/ labelled value assignment. This fixes the tokenizer walk on parser to accommodate for usage of ':' and '=' outside of role/ labelled value assignment. 
Also fixed issue reported in #1129.
- Added tests.
- Verified all existing tests pass.
> [Ludown] Parser fixes for composites and references to ':', '=' in utterances.

- package.json
This will let the Botbuilder-tools-js-CI-PR build upload to coveralls.io in a separate step from running tests. That lets us late-set the coveralls repo token, securing it from tests.
> Split "coveralls" into "coveralls" and "upload-coveralls"

- .gitignore
- packages/Ludown/lib/helpers.js
- packages/Ludown/lib/parseFileContents.js
- packages/Ludown/test/ludown.helpers.test.suite.js
- packages/Ludown/test/ludown.regexEntity.test.suite.js
Fixes #1177
Here is the log of trying to reproduce issue #1177 (in the WSL) after the changes from this PR:
```
$ cat /tmp/Slash.json
{
"luis_schema_version": "3.2.0",
"versionId": "0.1",
"name": "Slash",
"desc": "",
"culture": "en-us",
"tokenizerVersion": "1.0.0",
"intents": [
{
"name": "None"
}
],
"entities": [],
"composites": [],
"closedLists": [],
"patternAnyEntities": [],
"regex_entities": [
{
"name": "SlashEntity",
"regexPattern": "/:",
"roles": []
}
],
"prebuiltEntities": [],
"model_features": [],
"regex_features": [],
"patterns": [],
"utterances": [],
"settings": []
}
$ ./packages/Ludown/bin/ludown d -i /tmp/Slash.json  -o /tmp/ -n Slash.lu
$ cat /tmp/Slash.lu
> ! Automatically generated by [LUDown CLI](https://github.com/Microsoft/botbuilder-tools/tree/master/Ludown), Thu Jun 13 …
```
> [Ludown] Fix converting regex entities containing a slash followed by a colon

- packages/Ludown/lib/toLU-helpers.js
- packages/Ludown/test/verified/allGen.lu
- packages/Ludown/test/verified/allall-qna.lu
- packages/Ludown/test/verified/collate_refresh.lu
Fixes an issue where ludown refresh was lossy with converting LUIS model JSON to .lu file specifically for interchangeability of phrase lists. 
This PR fixes it. 
Updated existing tests.
> [Ludown] Refresh command now respects interchangeable flag

- packages/Ludown/docs/lu-file-format.md
The description for QnA notation should be wrapped in a markdown block. The content needed to be indented for proper scoping of the inner markdown block.
- Fixes description for LUDown QnA notation
> Fix notation description for QnA in LUDown

- packages/Ludown/README.MD
Fixes to correct property name for QnA content on `parseFile` output in LUDown README.
- Fixes the README for acccuracy
> Minor fix to code sample in LUDown README

- packages/LUISGen/package.json
With his last commit, Chrimc told me these tests should not be run. Currently they are breaking the build. (See Botbuilder-tools-js-CI-PR #67944. https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=67944&view=results ) (This corrects my mistake of disabling tests in the build when they should have been disabled in the code.)
If chrimc is available, he can review and approve/modify this PR. If not, I suggest we unblock the build by merging this, then let him weigh in when he returns.
> Disable failing tests in LUISGenTestJS. 

- packages/LUIS/package.json
- packages/LUISGen/src/LUISGen.csproj
- packages/LUISGen/src/npm/package.json
Bumps versions of tools to martch the 4.5 target release. Our target versions are:
Tool | Target
-- | --
LuisGen | 2.2.0
BotDispatch | 1.5.0
Chatdown | 1.2.3
Ludown | 1.3.2
luis-api | 2.6.0
qnamaker | 1.3.1
Msbot | 4.3.6
> Bump versions in prep for 4.5 release cycle

- packages/Ludown/lib/parseFileContents.js
- packages/Ludown/test/ludown.parsefile.test.suite.js
- packages/Ludown/test/ludown.roleTests.test.suite.js
Fixes #1151 
- Updated existing tests.
- Added new tests.
> Fix for #1151 - Allow phrase lists to have same name as other entity types in labelled utterances

- packages/Ludown/docs/commands.md
- packages/Ludown/docs/translate-command.md
- packages/Ludown/lib/ludown-translate.js
- packages/Ludown/lib/translate.js
Fixes #1211 
Ludown translate command provided an option for users to set an output lu_file name which was not respected. This PR fixes it. 
Verified existing tests pass.
> [Ludown] respect --lu_file option for translate command

- packages/Ludown/lib/translate-helpers.js
- packages/Ludown/test/ludown.translate.test.suite.js
Fixes #1191 
- QnA meta data filters were included in machine translation which results in incorrect behavior. This information should not be translated. This PR fixes it. 
Added new test to verify intended behavior.
> [Ludown] Skip QnA meta data filters from translation.

- .gitignore
- packages/MSLG/package-lock.json
- packages/MSLG/package.json
- packages/MSLG/src/Expander.ts
- packages/MSLG/src/Parser.ts
- packages/MSLG/test/mslg.cli.test.suite.js
Update lg package to the latest version in MSLG
> Update lg package in MSLG

- packages/lubuild/src/index.ts
* Multilingual dialog file is now saved without the ".." in the filename (e.g., no longer "sandwich..lu.dialog).
* Multilingual dialog file is now saved one level above the locale-specific dir (e.g, no longer saved to en_us/sandwich.lu.dialog, but one level up).
* If model training is required, check if "cachedResponses" dir exists at the same level as luconfig.json; if yes, remove it together with the content it holds.
Fixes #
- 
-
-
> Fixing file/directory related bugs

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Fixes #1445
Adds;
- Code of conduct doc (link to MS Community code of conduct)
- Contribution guidelines aligned with other SDK repos
> Adding / updating community docs

- README.md
Fixes #
#1516 
Added Dispatch deprecation verbiage on botbuilder-tools main README
> Update README.md - added Dispatch deprecation text and link to Orchestrator doc

- packages/LUIS/package-lock.json
- packages/LUIS/package.json
- packages/MSBot/package-lock.json
- packages/MSBot/package.json
- packages/QnAMaker/package-lock.json
- packages/QnAMaker/package.json
Fixes #minor
Botbuilder-tools-js-CI-PR is failing.
[Task npm run build](https://dev.azure.com/FuseLabs/SDK_v4/_build/results?buildId=300882&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=2c7de9cf-37f6-5488-01cf-84e0559e436a&l=100) fails with:
npm ERR! 404 Not Found - GET https://registry.npmjs.org/enum-files/-/enum-files-1.1.0.tgz
enum-files is no longer available on npmjs.com, but is available here:
https://github.com/hirowaki/enum-files
This switches to installing enum-files from GitHub instead of npmrc.com.
> Fix broken build Botbuilder-tools-js-CI-PR

- build/ExtractCompressNuGet.ps1
Fixes #minor
ExtractCompressNuGet.ps1, used in DotNet signing pipelines, fails with "Invoke-WebRequest : 404: Not Found" when it tries to install a powershell patch which is outdated and no longer available, 
This removes that patching code and instead ensures the correct Powershell.Archive minimum version is installed.
> Fix ExtractCompressNuGet.ps1 in tools
