microsoft/botbuilder-tools

.gitattributes, .gitignore, LUIS/bin/luis, LUIS/lib/api/serviceBase.js, LUIS/lib/help.js, LUIS/readme.md, LUIS/test/luis.cli.init.test.suite.js
cleaned up luis -init
cleaned up descriptions of things
=> change subscriptionKey -> authoringKey

ludown/README.MD, ludown/bin/ludown.js, ludown/lib/parseFileContents.js, ludown/lib/parser.js
Minor bug fixes, support '&" for refs. set cwd() as default folder
=> Minor bug fixes, support '&" for refs. set cwd() as default folder

QnAMaker/readme.md
better formatting @vishwacsena
=> edited QnaMaker readme

QnAMaker/.qnamakerrc, QnAMaker/.vscode/launch.json, QnAMaker/bin/qnamaker, QnAMaker/examples/createKnowledgeBase.json, QnAMaker/examples/generateAnswer.json, QnAMaker/examples/trainKnowledgeBase.json, QnAMaker/examples/updateKnowledgeBase.json, QnAMaker/lib/api/qnamaker.json, QnAMaker/lib/help.js, QnAMaker/lib/index.js, QnAMaker/package.json
Also --bot flag to output bot file
also ask --question to bypass goofy posting object for qenerate answer
=> make qnamaker have verb pattern like luis

Chatdown/readme.md, Dispatch/readme.md, LUIS/readme.md, MSBot/README.md, QnAMaker/readme.md, README.md, ludown/README.MD
And change header in [readme](https://github.com/Microsoft/botbuilder-tools/pull/81/files#diff-5d9ecf1241a92334f6019e677a83e767R1) for QnAMaker.
=> add badges for tools

Chatdown/Examples/BookTable-happyPath.chat, Chatdown/Examples/CommPreference.chat, Chatdown/Examples/Greeting.chat, Chatdown/Examples/QnA.chat, Chatdown/Examples/WhoAreYou.chat, Chatdown/Examples/cards/AskForLocation.json, Chatdown/Examples/cards/tableConfirmation.json, Chatdown/readme.md, MSBot/README.md, README.md
=> Readmeupdates

Dispatch/package.json
=> Updates to dispatch package.json

Chatdown/readme.md, Dispatch/readme.md, LUIS/readme.md, Ludown/README.MD, Ludown/lib/parseFileContents.js, MSBot/README.md, QnAMaker/readme.md
=> Fixes for bugs from bug bash

Ludown/package-lock.json, Ludown/package.json
=> updates to package.json for ludown

Chatdown/package-lock.json, Chatdown/package.json
=> chatdown new package

MSBot/src/BotConfig.ts, MSBot/src/models/botConfigModel.ts, MSBot/src/msbot-connect-azure.ts, MSBot/src/msbot-connect-dispatch.ts, MSBot/src/msbot-connect-endpoint.ts, MSBot/src/msbot-connect-file.ts, MSBot/src/msbot-connect-luis.ts, MSBot/src/msbot-connect-qna.ts, MSBot/src/msbot-disconnect.ts, MSBot/src/msbot-init.ts, MSBot/src/msbot-secret.ts
*Added the `secretKey` property to the BotConfigModel.ts 
*changed the 'Save' method to be lowercase
=> some small tweaks.

Ludown/examples/n4.lu, Ludown/examples/patterns1.lu, Ludown/lib/parser.js, Ludown/package-lock.json, Ludown/package.json
Ludown updates to handle 
- duplicate entity definitions
- pattern.any entity handling when different entity types are used in patterns
=> Ludown updates to handle duplicate entity definitions

MSBot/package.json
Included all `*.d.ts` files in the models directory.
=> Included the d.ts files for all models

MSBot/src/models/azureBotService.ts, MSBot/src/models/botConfigModel.ts, MSBot/src/models/connectedService.ts, MSBot/src/models/dispatchService.ts, MSBot/src/models/endpointService.ts, MSBot/src/models/fileService.ts, MSBot/src/models/luisService.ts, MSBot/src/models/qnaMakerService.ts, MSBot/src/msbot-connect-dispatch.ts, MSBot/src/msbot-connect-endpoint.ts, MSBot/src/msbot-connect-file.ts
added aliases for Ids on select models to prevent null Ids.
=> added aliases for Ids on select models

Chatdown/lib/index.js, Chatdown/package-lock.json, Chatdown/package.json
=> fix missing types

QnAMaker/lib/help.js, QnAMaker/package.json
=> fix --msbot help

LUIS/lib/api/Model/closedlists.js, LUIS/lib/api/serviceBase.js, QnAMaker/lib/api/UpdateAsync.js, QnAMaker/lib/api/endpointkeys.js, QnAMaker/lib/api/serviceBase.js
Http method PATCH requests made with fetch [apparently are case sensitive](https://github.com/github/fetch/issues/254). Otherwise, these calls fail.
=> Http method PATCH requests need to be UPPERCASE

Dispatch/package.json
updated version
Fixes #
- 
-
-
=> updated version for publishing

Dispatch/readme.md
updated prereq for Linux
Fixes #
- 
-
-
=> updated dotnet prereq link for Linux

Ludown/README.MD, Ludown/bin/ludown-parse-ToLuis.js, Ludown/bin/ludown-parse-ToQna.js, Ludown/bin/ludown-parse.js, Ludown/bin/ludown-refresh.js, Ludown/bin/ludown.js, Ludown/lib/helpers.js, Ludown/lib/parser.js, Ludown/lib/toLU.js, ludown/lib/enums/CLI-errors.js
Fixes #
- Snap to -v instead of -V for version information
- Updated all console.error to process.stdout.error
- Added specific process exit codes per error condition
- Removed dead code 
All tests pass
=> Code clean up - part 1

AzureCli/readme.md
=> fix formatting

Ludown/examples/12.lu, Ludown/lib/enums/luisobjenum.js, Ludown/lib/parseFileContents.js, Ludown/lib/parser.js, ludown/lib/enums/CLI-errors.js
Fixes #
- Fix collate – prebuilt are not getting through all the way (Carlo’s bug)
- Add patterns and pattern.any entity support
=> Ludown patterns

Dispatch/readme.md
update hierarchical default value
Fixes #
- 
-
-
=> update hierarchical default value

Ludown/README.MD, Ludown/examples/patterns1.lu, Ludown/lib/helpers.js, Ludown/lib/parseFileContents.js, Ludown/lib/parser.js, Ludown/package-lock.json, Ludown/package.json, Ludown/test/luis-patterns.js, Ludown/test/testcases/testcases-data.js, ludown/examples/fr-fr/changeAlarm.lu, ludown/examples/fr-fr/none.lu, ludown/examples/fr-fr/qna4.lu, ludown/examples/fr-fr/root.lu, ludown/lib/enums/CLI-errors.js
Fixes #
- Add return codes to README.MD
- Removed dead code & switched all exist comparisons to deep equal on a struct
- Enable patterns tests
- Verify phraselist dupe, mismatch of interchangeable
- Add sample and verify non en-us work (may be fr-fr)
- Test all samples to verify this would actually work with luis apps create
- Test all samples to verify this would work with qna maker GA 
- Published 1.0.12 to npm
All test cases passed. Patterns tests have been updated.
=> Ludown patterns vk

Ludown/lib/parser.js, Ludown/lib/toLU.js, Ludown/package-lock.json, Ludown/package.json
Fixes #
- #167 
Verified all tests pass.
=> Ludown utf fix

Ludown/lib/parser.js, Ludown/package-lock.json, Ludown/package.json
Fixes #
Typo with readFileSync - should be readSync()
=> Updates to fix file read

Ludown/lib/parseFileContents.js, Ludown/lib/toLU.js, Ludown/package-lock.json, Ludown/package.json
Fixes #187 
All tests are passing.
=> Ludown fix

Ludown/bin/ludown-parse-ToLuis.js, Ludown/bin/ludown-parse-ToQna.js, Ludown/bin/ludown-parse.js, Ludown/bin/ludown-refresh.js, Ludown/bin/ludown.js, Ludown/package-lock.json, Ludown/package.json
=> Fix for #207

Ludown/bin/ludown-parse-ToLuis.js, Ludown/bin/ludown-parse-ToQna.js, Ludown/package-lock.json, Ludown/package.json
=> Ludown fix 220

Ludown/ChitChat/DataSet/Friendly/AboutBot.lu, Ludown/ChitChat/DataSet/Friendly/AboutUser.lu, Ludown/ChitChat/DataSet/Friendly/Command.lu, Ludown/ChitChat/DataSet/Friendly/Compliment.lu, Ludown/ChitChat/DataSet/Friendly/Criticism.lu, Ludown/ChitChat/DataSet/Friendly/Dialog.lu, Ludown/ChitChat/DataSet/Friendly/Greeting.lu, Ludown/ChitChat/DataSet/Friendly/Relationship.lu, Ludown/ChitChat/DataSet/Humorous/AboutBot.lu, Ludown/ChitChat/DataSet/Humorous/AboutUser.lu, Ludown/ChitChat/DataSet/Humorous/Command.lu, Ludown/ChitChat/DataSet/Humorous/Compliment.lu, Ludown/ChitChat/DataSet/Humorous/Criticism.lu, Ludown/ChitChat/DataSet/Humorous/Dialog.lu, Ludown/ChitChat/DataSet/Humorous/Greeting.lu, Ludown/ChitChat/DataSet/Humorous/Relationship.lu, Ludown/ChitChat/DataSet/Professional/AboutBot.lu, Ludown/ChitChat/DataSet/Professional/AboutUser.lu, Ludown/ChitChat/DataSet/Professional/Command.lu, Ludown/ChitChat/DataSet/Professional/Compliment.lu, Ludown/ChitChat/DataSet/Professional/Criticism.lu, Ludown/ChitChat/DataSet/Professional/Dialog.lu, Ludown/ChitChat/DataSet/Professional/Greeting.lu, Ludown/ChitChat/DataSet/Professional/Relationship.lu, Ludown/ChitChat/DataSet/README.MD, Ludown/README.MD
Adding small talk/ chit-chat asset .lu files. This enables developers to easily seed small talk capabilities to their bot using simple .lu files and using [qnamaker.ai](https://qnamaker.ai).
=> Adding small talk/ chit-chat assets

BuildUtilities/PushBitsToGithub.ps1
=> Comment added.

Ludown/lib/toLU.js, Ludown/package-lock.json, Ludown/package.json
Fixes #189 
All tests are passing.
=> Fix#189 - multiple entities in an utterance can break ludown refresh

Ludown/bin/ludown-translate.js, Ludown/lib/translate.js, Ludown/package-lock.json, Ludown/package.json
Publishing to npm with ludown translate command support.
=> Publishing v1.0.30 with translate command support

Chatdown/readme.md
Modified the markdown formatting so that the message command section displays properly.
=> Fixed the message command section table layout

Chatdown/.vscode/launch.json, Chatdown/lib/index.js, Chatdown/package.json
Fixes #270 
Set text to empty string.  There is logic which won't emit messages with empty strings already.
=> fix undefined text after conversationUpdate

QnAMaker/lib/api/dataModels/wordAlterationsDto.js, QnAMaker/package-lock.json, QnAMaker/package.json
=> Fix for #272 

LUIS/bin/luis, LUIS/lib/api/index.js, LUIS/package-lock.json, LUIS/package.json, LUIS/test/luis.cli.help.test.suite.js, LUIS/test/luis.cli.init.test.suite.js, LUIS/test/luis.cli.invalidArgs.test.suite.js, LUIS/test/mocha.opts, build.ci.sh
- Update all LUIS cli tests to match with the actual code.
- Enable tests in Travis-CI.
=> Fix LUIS cli tests

Chatdown/package.json, Chatdown/test/chatdown.cli.test.suite.js, Chatdown/test/mocha.opts, LUIS/test/mocha.opts, build.ci.sh
Enable Coveralls integration for coverage instrumentation.
Once merged the coverage metrics will be published https://coveralls.io/github/Microsoft/botbuilder-tools
=> Enable Coverall integration

QnAMaker/package-lock.json, QnAMaker/package.json, QnAMaker/test/mocha.opts, QnAMaker/test/qnamaker.cli.help.test.suite.js, QnAMaker/test/qnamaker.cli.init.test.suite.js, build.ci.sh
- Update all QnA Maker CLI tests to match with the actual code.
- Enable tests in Travis-CI.
=> Fix QnA Maker CLI tests

build.ci.sh
Fix the issue related to the daily builds that are not being published due to changes in the directory structure.
=> Daily build with lerna

packages/Ludown/lib/parser.js, packages/Ludown/package-lock.json, packages/Ludown/package.json
=> Fixing ludown to exclude appending .json if user has already specified extension

packages/Ludown/lib/parser.js
Fixes build
- Related to PR #364 which broke the build
Travis build should pass again
=> Check file extension before adding output suffix

packages/MSBot/src/BotConfig.ts, packages/MSBot/src/msbot-connect-azure.ts, packages/MSBot/src/msbot-connect-dispatch.ts, packages/MSBot/src/msbot-connect-endpoint.ts, packages/MSBot/src/msbot-init.ts
- Replaced double equals with triple equals as TSLint suggested.
=> Fixed TSLint 'triple-equals' warnings in MSBot

README.md, lerna.json, package-lock.json, package.json
Force `lerna@3.2.1` due to an issue with the license of future versions.
=> Use lerna 3.2.1 as default

packages/LUIS/.vscode/tasks.json, packages/LUIS/bin/luis, packages/MSBot/.vscode/launch.json, packages/MSBot/package-lock.json, packages/MSBot/package.json, packages/MSBot/src/msbot-clone.ts, packages/MSBot/src/msbot-connect-appinsights.ts, packages/MSBot/src/msbot-connect-dispatch.ts, packages/MSBot/src/msbot-connect-file.ts, packages/MSBot/src/msbot-connect-generic.ts, packages/MSBot/src/msbot-connect-qna.ts, packages/MSBot/src/msbot-export.ts, packages/MSBot/src/msbot-get.ts, packages/MSBot/src/msbot-init.ts, packages/MSBot/src/msbot-list.ts, packages/MSBot/src/msbot-secret.ts, packages/MSBot/src/msbot.ts, packages/MSBot/src/processUtils.ts, packages/MSBot/src/utils.ts, packages/MSBot/tests/commandTests.js, packages/MSBot/tests/connectTests.js, packages/MSBot/tests/disconnectTests.js
This implements clone for all service types
* LUIS
* QNA
* Blob
* Bot
* AppInsights
* File
* Generic
* CosmosDB 
* Dispatch
Requires branch tomlm/export in botbuilder-js
=> Implement msbot clone

build.ci.sh, packages/LUIS/package.json
Fixes #392 
- Update publish script to generate the `.js` sources for `msbot` and `luis-apis` tools.
=> Fix msbot and luis-apis publish issue

packages/MSBot/src/msbot-connect-appinsights.ts
The following issues have been fixed:
- typedef
- no-any
- interface-name
- quotemark
- no-empty
- prefer-const
- one-line
- curly
- triple-equals
- no-var-keyword
- forin
- newline-before-return
- eofline
A key had to be added to `IConnectAppInsightsArgs` to be able to iterate through its properties.
=> Fix TSLint issues in msbot-connect-appinsights.ts

packages/MSBot/src/msbot-connect-cosmosdb.ts
Fix the following warnings in the file `msbot-connect-cosmosdb.ts`:
- `typedef`
- `no-any`
- `quotemark`
- `no-empty`
- `one-line`
- `curly`
- `eofline`
=>  Fix TSLint warnings in msbot-connect-cosmosdb.t

packages/MSBot/src/msbot-connect-file.ts
The following TSLint issues has been fixed in `msbot-connect-file.ts`:
- typedef
- no-any
- interface-name
- curly
- prefer-const
- no-object-literal-type-assertion-
- newline-before-return
- one-line
- eofline
A key had to be added to `IConnectFileArgs` to be able to iterate through its properties. The type of the key had to be `any` because otherwise it needed to be `undefined` which caused a `Object is possibly 'undefined'.` error in the loop logic.
=> Fix TSLint issues in msbot-connect-file.ts

packages/MSBot/package.json, packages/MSBot/src/msbot-clone.ts, packages/MSBot/src/msbot-connect-bot.ts, packages/MSBot/src/msbot-connect-cosmosdb.ts, packages/MSBot/test/bot.txt, packages/MSBot/test/msbot.connect.test.suite.js
=> Change msbot to support cosmosdb key/endpoint and bot appid

packages/.vscode/tasks.json, packages/LUIS/package.json, packages/MSBot/.gitignore, packages/MSBot/package-lock.json, packages/MSBot/package.json, packages/MSBot/tsconfig.json
made sure directories are defined correctly
made sure files are defined correctly
put typings in typings folder
verified npm pack is actually picking up all required files.
=> cleanup packages

README.md, packages/Chatdown/readme.md, packages/Dispatch/readme.md, packages/MSBot/README.md
Fixes several broken links.
- Fixed all links broken after moving tools to `packages` folder due to `lerna` integration
- Fixed several typos
No broken links should appear in docs
=> Review and fix tools docs

packages/LUIS/bin/help.js, packages/LUIS/bin/luis.js, packages/QnAMaker/bin/qnamaker.js, packages/QnAMaker/lib/help.js
Fixes #431 
QnAMaker delete  takes a --force flag
luis  delete takes a --force flag
=> add --force flag to delete operations

packages/MSBot/src/msbot-clone.ts
- Disable all TSLint rules in msbot-clone.ts
=> Disable all TSLint rules in msbot-clone.ts

build.ci.sh, package.json
- Run tests before check ESLint rules.
- Disable ESLint indent rule.
=> Run tests before check ESLint rules

packages/LUIS/bin/luis.js
=> add version fallback for versionId

packages/LUIS/bin/luis.js
=> add --msbot to import version

packages/MSBot/.vscode/launch.json, packages/MSBot/README.md, packages/MSBot/src/msbot-clone-services.ts, packages/MSBot/src/msbot-update-appinsights.ts, packages/MSBot/src/msbot-update-blob.ts, packages/MSBot/src/msbot-update-cosmosdb.ts, packages/MSBot/src/msbot-update-dispatch.ts, packages/MSBot/src/msbot-update-endpoint.ts, packages/MSBot/src/msbot-update-generic.ts, packages/MSBot/src/msbot-update-luis.ts, packages/MSBot/src/msbot-update-qna.ts, packages/MSBot/src/msbot-update.ts, packages/MSBot/src/msbot.ts, packages/MSBot/test/msbot.update.test.suite.js
Fixes #363 
added msbot update xxxx where xxxx is a service
* blob
* appInsights
* cosmosdb
* luis
* dispatch
* endpoint
* generic
=> add msbot update commands

packages/MSBot/src/msbot-connect-generic.ts, packages/MSBot/src/msbot-secret.ts, packages/MSBot/src/msbot-update-generic.ts
=> Fix #477 msbot secret -n outputs object

packages/MSBot/src/msbot-connect-dispatch.ts, packages/MSBot/src/msbot-update-appinsights.ts, packages/MSBot/src/msbot-update-blob.ts, packages/MSBot/src/msbot-update-cosmosdb.ts, packages/MSBot/src/msbot-update-dispatch.ts, packages/MSBot/src/msbot-update-endpoint.ts, packages/MSBot/src/msbot-update-generic.ts, packages/MSBot/src/msbot-update-luis.ts, packages/MSBot/src/msbot-update-qna.ts, packages/MSBot/test/msbot.update.test.suite.js
https://github.com/Microsoft/botbuilder-tools/issues/484
* allow update to take --id so you can patch service by id
* allow update to patch any property
=> Fix for #484

packages/MSBot/src/msbot-clone-services.ts
=> MsBot: Default Luis service uses _ instead of - to not break luisgen

packages/LUIS/bin/luis.js
Fixes #438 
Verified the commands listed in the bug all work correctly with the fix
=> fixes #438

packages/Ludown/lib/parseFileContents.js, packages/Ludown/lib/parser.js, packages/Ludown/test/ludown.filereferences.test.suite.js, packages/Ludown/test/ludown.qnafiles.test.suite.js, packages/Ludown/test/testcases/root3.lu, packages/Ludown/test/verified/root3.lu
Fixes #524
- added one additional test
- all existing tests are passing
=> Fix for #524

packages/MSBot/src/msbot-export-services.ts
Fixes #551 
add missing option
=> export services missing --secret argument

packages/MSBot/src/msbot-clone-services.ts
=> MsBot: Fix undefined storage info error

packages/Chatdown/bin/chatdown.js, packages/LUIS/bin/luis.js, packages/LUIS/package-lock.json, packages/LUIS/package.json, packages/MSBot/package-lock.json, packages/MSBot/src/msbot-connect-appinsights.ts, packages/MSBot/src/msbot-connect-blob.ts, packages/MSBot/src/msbot-connect-bot.ts, packages/MSBot/src/msbot-connect-cosmosdb.ts, packages/MSBot/src/msbot-connect-dispatch.ts, packages/MSBot/src/msbot-connect-endpoint.ts, packages/MSBot/src/msbot-connect-file.ts, packages/MSBot/src/msbot-connect-generic.ts, packages/MSBot/src/msbot-connect-luis.ts, packages/MSBot/src/msbot-connect-qna.ts, packages/MSBot/src/msbot-disconnect.ts, packages/MSBot/src/msbot-export-services.ts, packages/MSBot/src/msbot-update-appinsights.ts, packages/MSBot/src/msbot-update-blob.ts, packages/MSBot/src/msbot-update-cosmosdb.ts, packages/MSBot/src/msbot-update-dispatch.ts, packages/MSBot/src/msbot-update-endpoint.ts, packages/MSBot/src/msbot-update-generic.ts, packages/MSBot/src/msbot-update-luis.ts, packages/MSBot/src/msbot-update-qna.ts, packages/MSBot/src/processUtils.ts, packages/MSBot/src/stdioAsync.ts, packages/QnAMaker/bin/qnamaker.js
Fixes #548 
Changed to use a Promise() around the call back so we can easily await the output of the program before calling process.exit()
=> on mac if you call process.exit() without waiting for console callback it will truncate the output

packages/LUIS/bin/luis.js, packages/LUIS/package-lock.json, packages/LUIS/package.json, packages/MSBot/package-lock.json, packages/MSBot/package.json, packages/MSBot/src/msbot-clone-services.ts, packages/MSBot/src/utils.ts
Fixes #553 
* msbot clone lists all services that will be created on your behalf
* -q will suppress
* luis is more robust to training outage
* luis training shows models and status as part of training
* msbot clone doesn't fail it training fails, but gives warning to user.
* Also adds region->SearchRegion map so that search creation doesn't fail on odd regions
=> Add sku/pricing info at start

packages/LUISGen/src/LUISGen/LUISGen.csproj
=> remove global versioning

package-lock.json, packages/Chatdown/package-lock.json, packages/Chatdown/test/cli.transcript, packages/Chatdown/test/sample.transcript, packages/Dispatch/package-lock.json, packages/LUIS/package-lock.json, packages/LUISGen/package.json, packages/LUISGen/tests/LUISGenTestJS/package-lock.json, packages/LUISGen/tests/LUISGenTestJS/package.json, packages/MSBot/package-lock.json, packages/QnAMaker/bin/qnamaker.js
Fixes lerna botframework version not being there and re-hoists depdencies
=> fix lerna packages

build.ci.sh, package-lock.json, packages/Chatdown/package-lock.json, packages/Chatdown/test/cli.transcript, packages/Chatdown/test/sample.transcript, packages/Dispatch/package-lock.json, packages/LUIS/package-lock.json, packages/LUISGen/package.json, packages/LUISGen/tests/LUISGenTestJS/package-lock.json, packages/LUISGen/tests/LUISGenTestJS/package.json, packages/LUISGen/tests/LUISGenTestJS/src/tests.ts, packages/MSBot/package-lock.json, packages/QnAMaker/bin/qnamaker.js
Fixes #621
- Cleanup LUISGenTestJS
- Update build.ci.sh for LUISGen (JS) tests 
- Disable .net LUISGen tests
=> Fix Build breaks

packages/Ludown/test/testcases/translate-testcase-data.js, packages/Ludown/test/verified/de/all.lu
Fixing ludown failing tests.
Translator services has started returning slightly different results. Updating tests.
=> Fixing translator tests

packages/Ludown/docs/translate-command.md, packages/Ludown/lib/ludown-translate.js, packages/Ludown/lib/translate-helpers.js, packages/Ludown/lib/translate.js, packages/Ludown/test/ludown.translate.test.suite.js, packages/Ludown/test/testcases/reduced.lu, packages/Ludown/test/testcases/translate-testcase-data.js, packages/Ludown/test/verified/de/all.lu, packages/Ludown/test/verified/de/reduced.lu, packages/Ludown/test/verified/zh-Hans/reduced.lu
Fixes 
- #636 
- #638 
- Added new tests
- Updated existing tests
- All tests are passing
=> Ludown fix for #636 and #638

packages/MSBot/README.md, packages/MSBot/docs/botframework-configuration.md
Fixes a bunch of links  in the "how to consume .bot files" page
=> Fix links to various repos

packages/MSBot/src/msbot-update-luis.ts, packages/MSBot/test/msbot.update.test.suite.js
=> Updated msbot update luis to include check / update of version number.

packages/MSBot/package-lock.json, packages/MSBot/package.json
Updating `linq-collections` package:
- performance improvements + adds support for `SequenceEqual`, `DefaultIfEmpty`, `TakeWhile`, ...
=> Update Linq-Collections package

packages/LUIS/bin/help.js
Fixes #631 
- added description for --subscriptionKey in help
=> added description for --subscriptionKey in help

packages/MSBot/docs/bot-file-encryption.md
Fixes #674 
Added steps to (re)set bot file secret in portal.azure.com
Docs change only. no tests were added or updated.
=> Fix for #674

packages/Ludown/docs/commands.md, packages/Ludown/docs/refresh-command.md, packages/Ludown/docs/translate-command.md
- Add `--prefix` switch description to docs
Review docs in [Ludown/docs](https://github.com/Microsoft/botbuilder-tools/tree/master/packages/Ludown/docs)
=> Update ludown docs to include prefix switch

packages/Dispatch/package.json
=> upversioned  package.json

packages/LUIS/bin/luis.js
Fixes #627
- Add `list querylogs` case for `luis.js`.
- Handle streamed responses from `ms-rest-js`.
`luis list querylogs` csv response
=> [LUIS] Fix querylogs download handling 

packages/MSBot/src/msbot-clone-services.ts
fixes grammatical error in help text
=> fix msbot clone help text

packages/MSBot/README.md
=> fix small grammatical error

packages/Ludown/lib/translate-helpers.js, packages/Ludown/test/ludown.translate.test.suite.js, packages/Ludown/test/testcases/faq.lu, packages/Ludown/test/verified/de/all.lu, packages/Ludown/test/verified/de/faq.lu
Fixes #707 
- Fix to handle markdown segments in QnA Maker answer for ludown translate command
- Added new tests 
- Updated one existing test
=> Ludown: Fix for correct handling of markdown segments in QnA answer for translate command

packages/Ludown/docs/commands.md, packages/Ludown/docs/translate-command.md, packages/Ludown/lib/classes/hclasses.js, packages/Ludown/lib/ludown-translate.js, packages/Ludown/lib/translate-helpers.js, packages/Ludown/lib/translate.js, packages/Ludown/test/ludown.cli.test.suite.js, packages/Ludown/test/verified/de/all.lu, packages/Ludown/test/verified/de/faq.lu
Fixes #695 and #642 
- Implemented batching for calls to translation service
- Provided an over-ride for customers to set a lower batch size (if required)
- Improves translate perf by up to 10x
- Updated existing tests
- No new tests added since there is no functional change.
=> Ludown: Batching calls to translate service. Improves ludown translate perf by 10x

packages/MSBot/docs/export-clone.md
=> MsBot: Add the Appid and app password parameters to documentation

packages/MSBot/src/msbot-clone-services.ts
Fixes #736
Correctly pass the subscriptionId through to the az commands
=> Fix msbot clone ignoring --subscriptionId parameter

packages/MSBot/docs/msbot-az.md
Fixes https://github.com/Microsoft/botbuilder-tools/issues/738
Changes
Added note to use latest version of AZ CLI for MSBot to work properly.
=> Update MSBot readme

packages/Ludown/docs/commands.md, packages/Ludown/docs/refresh-command.md, packages/Ludown/lib/ludown-refresh.js, packages/Ludown/lib/toLU.js, packages/Ludown/package-lock.json, packages/Ludown/package.json, packages/Ludown/test/ludown.cli.test.suite.js, packages/Ludown/test/ludown.examples.test.suite.js, packages/Ludown/test/verified/stdin-qna.lu, packages/Ludown/test/verified/stdin.lu
- added --stdin and --stdout ability to ludown refresh command
- verified existing tests are passing. 
- added new tests.
=> Ludown: Add ability to generate a lu file from stdin as well as write to stdout

packages/Ludown/docs/lu-file-format.md, packages/Ludown/examples/luFileReference6.lu, packages/Ludown/lib/helpers.js, packages/Ludown/lib/parser.js, packages/Ludown/test/ludown.examples.test.suite.js, packages/Ludown/test/testcases/ref7.lu, packages/Ludown/test/testcases/ref8.lu, packages/Ludown/test/verified/ref7.json, packages/Ludown/test/verified/ref8.json
Fixes #752 
Per offline feedback from @lauren-mills, added
- *patterns* and *utterancesAndPatterns* support to ludown deep references.
- Verified that existing tests are passing
- Added new tests for new functionality
=> Ludown: Added *patterns* and *utterancesAndPatterns* support to deep ref.

packages/QnAMaker/lib/api/serviceBase.js
=> resolves #761 - Added the User-Agent header to all outbound calls

packages/MSBot/docs/add-services.md, packages/MSBot/src/msbot-connect-appinsights.ts, packages/MSBot/src/msbot-update-appinsights.ts
=> MsBot: Remove duplicate app insights short param, leave as-is consistent

packages/MSLG/lib/api/mslg.json
Fixes replace command in the LG branch 
https://lgtools.visualstudio.com/LG%20For%20Bots/_workitems/edit/74/
=> Fix replace command

packages/Chatdown/lib/index.js, packages/Chatdown/test/cli.transcript, packages/Chatdown/test/sample.transcript
Fixes #787 
All existing tests pass
=> Chatdown: Do not force card content to lower case

packages/LUIS/package-lock.json, packages/LUIS/test/luis.cli.help.test.suite.js, packages/LUIS/test/luis.cli.test.suite.js
Fixes #788 
- PR #788 updated the query command for LUIS which broke few tests. This PR addresses it. 
- Verified that all LUIS tests are passing locally.
=> Fixing failing tests related to #788

packages/MSLG/bin/mslg.js, packages/MSLG/docs/autor-models-tutorial.md, packages/MSLG/examples/ModelDefinition.json, packages/MSLG/lib/api/endpoints.js, packages/MSLG/lib/api/locales.js, packages/MSLG/lib/api/models.js, packages/MSLG/lib/api/mslg.json, packages/MSLG/lib/utils/helpers.js, packages/MSLG/swagger.json, packages/MSLG/test/TestData/definitions/modelDefinition.json, packages/MSLG/test/TestData/definitions/modelDefinitionWithoutText.json, packages/MSLG/test/mslg.cli.init.test.js
Fixes 
https://lgtools.visualstudio.com/LG%20For%20Bots/_workitems/edit/80
- Update to v2.0 
- Update default version to `0.1` from `default`
- Print out resolver application inputs when creating model or endpoint
=> Upgrade to LG v2.0

packages/QnAMaker/lib/api/serviceBase.js
update user-agent for qnamaker
=> update user-agent for qnamaker

packages/MSBot/src/msbot-clone-services.ts, packages/MSBot/src/msbot-create.ts
We need to make sure they have at least version 2.1.500 installed
=> Add dotnet version check to catch old versions of DOTNET floating around

packages/MSBot/src/msbot-clone-services.ts
We always want to give unique app name to LUIS apps
Fixes #857
=> Remove decorate remnant

packages/MSBot/package.json
- bump patch version in order to publish decorator fix
=> MSBot bump patch version to 4.3.1

packages/MSBot/src/msbot-clone-services.ts
- Remove unneeded botservice module checking. By moving away from the azure-cli-extension process, the version number of botservice is tightly coupled to the version of azure-cli. 
- Add warning message to users using msbot clone services to make sure they don't have the old botservice extensions installed, and provide the command needed to remove the extension.
- Small optimization: `break;` after we find `"azure-cli"` in the stdout of `az -v`, we only need the azure-cli version number.
=> msbot: clone only checks for the AZ CLI version, some optimizing

packages/Ludown/test/ludown.parsetranslate.test.suite.js
Disable the `Intents and utterances are translated correctly` test.
=> Disable loc test

packages/Ludown/lib/parseFileContents.js, packages/Ludown/test/verified/12qna.json, packages/Ludown/test/verified/all-qna.json, packages/Ludown/test/verified/allGenQnA.lu, packages/Ludown/test/verified/allall-qna.lu, packages/Ludown/test/verified/collate-qna.json, packages/Ludown/test/verified/collate_refresh.lu, packages/Ludown/test/verified/root.json, packages/Ludown/test/verified/root2.json
=> Remove trailing /r/n from answers when parsing to QnA.

packages/LUIS/bin/luis.js
=> Consistent ordering of patterns and pattern entities.

packages/LUISGen/src/Program.cs, packages/LUISGen/src/npm/readme.md, packages/LUISGen/tests/LUISGenTest/LUISGenTest.csproj, packages/LUISGen/tests/LUISGenTest/TestData/TestApp.json, packages/LUISGen/tests/LUISGenTest/Tests.cs
Fixes #856 
- Added LuisGen `--stdin` parameter to signal to read off input from stdin.
- Updated docs to reflect usage.
- Added new unit test for testing `--stdin` functionality in command line args parsing.
=> Fix LuisGen input stdin issue #856

packages/MSBot/docs/update-service.md
This should be chaged from applicationId -> appId.
Fixes #
- 
-
-
=> Update dispatch requirement argument

packages/MSBot/package-lock.json, packages/MSBot/src/msbot-clone-services.ts, packages/MSBot/src/msbot-create.ts
Fixes https://github.com/Microsoft/botbuilder-tools/issues/584
add --searchSku flag to control the sku for search
=> [msbot] add searchSku to options

packages/MSBot/docs/export-clone.md
Fixes [Issue 906](https://github.com/Microsoft/botbuilder-tools/issues/906)
Added missing msbot clone services options.
=> Added missing options

packages/MSBot/src/msbot.ts
Fixes #933 
I used incorrect semver syntax.  It's **^version** not **>version**
=> fix semver bug

packages/MSBot/src/msbot-clone-services.ts
Update maxBuffer size for runCommand to 2MB
Fixes #873
=> Update maxBuffer size for runCommand

packages/Chatdown/readme.md, packages/Dispatch/readme.md, packages/LUIS/readme.md, packages/Ludown/README.MD, packages/QnAMaker/readme.md
Changed Readme with package names for all the packages.
=> Changed readme's with correct package names

packages/MSBot/package.json
- bump version number for 4.3 release
=> Bump MSBot version number to 4.3.4

packages/LUIS/package.json
=> Update luis cli package.json on master branch

packages/Ludown/docs/lu-file-format.md, packages/Ludown/examples/compositeEntities.lu, packages/Ludown/lib/classes/hclasses.js, packages/Ludown/lib/enums/CLI-errors.js, packages/Ludown/lib/enums/luisobjenum.js, packages/Ludown/lib/helpers.js, packages/Ludown/lib/parseFileContents.js, packages/Ludown/lib/parser.js, packages/Ludown/lib/toLU-helpers.js, packages/Ludown/lib/toLU.js, packages/Ludown/test/ludown.classes.test.suite.js, packages/Ludown/test/ludown.compositeEntity.test.suite.js, packages/Ludown/test/ludown.examples.test.suite.js, packages/Ludown/test/ludown.parsefile.test.suite.js, packages/Ludown/test/ludown.roleTests.test.suite.js, packages/Ludown/test/ludown.tolu.test.suite.js
Fixes #1042 
- Added support for explicit role definition with entity type definition
- Added support for roles in labelled utterances
Note: This also includes relevant changes for composite entity support addressed via #1041 
- Added new tests to cover all new code added
- Updated existing tests where needed
- Verified all tests pass.
=> [Ludown] Support for roles in entity definition and in labelled utterances

packages/Ludown/docs/lu-file-format.md, packages/Ludown/examples/compositeEntities.lu, packages/Ludown/lib/classes/hclasses.js, packages/Ludown/lib/enums/CLI-errors.js, packages/Ludown/lib/enums/luisobjenum.js, packages/Ludown/lib/helpers.js, packages/Ludown/lib/parseFileContents.js, packages/Ludown/lib/parser.js, packages/Ludown/lib/toLU-helpers.js, packages/Ludown/lib/toLU.js, packages/Ludown/test/ludown.classes.test.suite.js, packages/Ludown/test/ludown.compositeEntity.test.suite.js, packages/Ludown/test/ludown.examples.test.suite.js, packages/Ludown/test/ludown.parsefile.test.suite.js, packages/Ludown/test/ludown.tolu.test.suite.js
Fixes #1009
- Implemented support for composite entities in .lu file format and in the ludown tool per spec defined in #1009 
- Added new test to cover new/ changed code
- Verified all existing tests pass
- Updated existing tests where needed.
=> [Ludown] Support for composite entities in .lu file format and ludown CLI

packages/LUIS/bin/luis.js
=> Fixes incorrect API calls around LUIS suggest intents

packages/MSBot/package.json, packages/MSBot/src/msbot-connect-dispatch.ts, packages/MSBot/src/msbot-update-dispatch.ts
Fixes #977 
update command line help for --region flag
bump version number
=> fix 977 region flag help text is not correct

packages/LUIS/bin/luis.js
=> LUIS AddAppAzureAccount inline alternative

packages/Chatdown/test/chatdown.cli.test.suite.js
when we run unit tests as part of build with a preview tag it triggers notices for upgrade which breaks unit tests only in the context of a preview build
- Changed the unit tests to be aware of upgrade notice.
- this is in the unit tests
=> fix unit tests when version triggers upgrade notice

packages/Ludown/test/ludown.examples.test.suite.js
Verified all tests are passing locally on a windows machihe.
=> [Ludown] Fixing tests only passed on *nix machines

packages/lubuild/luconfig.json, packages/lubuild/src/help.ts, packages/lubuild/src/index.ts
added new commands
- lubuild add foo.lu --> update luconfig.json models
- lubuild remove foo.lu --> remove lu file from luconfig.json.models
Also now pick up authoring key from environment and .luisrc files if not on command line args.
=> lubuild add and lubuild remove commands

packages/Dispatch/package.json, packages/Dispatch/readme.md
=> upversion package.json and updated readme

packages/DialogSchema/src/dialogSchema.schema
Change meta-schema to point to master branch.
Passes all dialogSchema tests.
=> Change meta-schema to point to master instead of schemaGen.

packages/MSLG/README.MD
Updated Readme.md to fix a broken link.
=> [MSLG CLI] Update readme.md to fix broken link

packages/DialogDebugger.VSCode/package.json
=> Update publisher to microsoft

packages/MSLG/package-lock.json, packages/MSLG/test/mslg.cli.test.suite.js
=> [MSLG]fix build failure and test failures

packages/Ludown/package.json
Bumps Ludown version in prep for publishing. PArt of the fix for:
#1135 
#1129
=> Bump Ludown version in prep for emergent push

README.md
=> Set build badge to reflect Botbuilder-tools-js-daily

packages/MSLG/package-lock.json, packages/MSLG/src/Translator.ts, packages/MSLG/src/helpers.ts, packages/MSLG/test/mslg.cli.test.suite.js
Reverts microsoft/botbuilder-tools#1144
=> Revert "[MSLG] update lg package and related changes"

packages/Dispatch/package-lock.json, packages/Dispatch/package.json, packages/Dispatch/readme.md
Fixes #
Expose optional param (to the "add" command) to include qna answers for training.
- 
-
-
=> added optional param to "add" command

build/PublishToCoveralls.ps1
This allows publishing coverage to coveralls.io.
=> Add build\PublishToCoveralls.ps1

packages/LUISGen/src/CSharp.cs, packages/LUISGen/src/LUISGen.csproj, packages/LUISGen/src/Typescript.cs, packages/LUISGen/src/Utils.cs, packages/LUISGen/src/npm/package.json
Fixes #1107 
Made LUISGen robust to properties missing from export file.
=> Make LUISGen more robust to the presence/absence of features.

packages/LUISGen/src/LUISGen.csproj, packages/LUISGen/src/npm/package.json
npm install code did not globally install LUISGen so need to update versions.
=> Update versions to 2.1.2.

README.md
Fixes #1140
Fixes #1160 
Remove `dialogtracker dialogschema dialoglint` from Master branch README.
=> removed future tools from README

packages/Dispatch/package.json
=> Updated version for Dispatch fix (case sensitive entities dupe check)

packages/MSBot/docs/bot-file-encryption.md
Fixes
- Fixes grammar mistake.
=> Fixes grammar

packages/Chatdown/package-lock.json, packages/Chatdown/package.json, packages/Dispatch/package-lock.json, packages/Dispatch/package.json, packages/LUIS/package-lock.json, packages/LUIS/package.json, packages/LUISGen/src/npm/package-lock.json, packages/LUISGen/src/npm/package.json, packages/Ludown/package-lock.json, packages/Ludown/package.json, packages/MSBot/package-lock.json, packages/MSBot/package.json, packages/QnAMaker/package-lock.json, packages/QnAMaker/package.json
This will give ongoing preview packages proper versioning.
=> Roll js package versions to be 1 higher than their release versions.

packages/Dispatch/readme.md
Added "true" after "includeAnswersForTraining" add qna sample command
Fixes #
- 
-
-
=> Minor update readme.md

packages/Dispatch/package.json
=> upversion for CpuMathNative.dll dependency fix

.gitignore, packages/Ludown/lib/helpers.js, packages/Ludown/lib/parseFileContents.js, packages/Ludown/test/ludown.helpers.test.suite.js, packages/Ludown/test/ludown.regexEntity.test.suite.js
=> Merge fork: Fix converting regex entities containing a slash followed by a colon #1178

packages/Ludown/lib/classes/hclasses.js, packages/Ludown/lib/helpers.js, packages/Ludown/lib/parseFileContents.js, packages/Ludown/test/ludown.cli.test.suite.js, packages/Ludown/test/ludown.compositeEntity.test.suite.js, packages/Ludown/test/ludown.parsefile.test.suite.js, packages/Ludown/test/ludown.roleTests.test.suite.js
- #1137 
- #1151
- #1164
- #1165
- #1166 
- #1167 
- Verified existing tests pass
- Removed obsolete tests where necessary
- Added new tests
=> [Ludown] Fixes for several bugs related to roles and composites

packages/MSBot/docs/bot-file-encryption.md
-  Adds inline code styles around flags/switches in the bot-file-encryption guide so that they are displayed consistently throughout.
=> Adds code styles around flags for consistency

packages/LGvscodeExt/resources/lgPreviewTemplate.html, packages/LGvscodeExt/src/providers/debugPanel.ts
Fixes #
- change the display of template name and free text input 
- users can select the source of the template they want to evaluate from
- all the available template names can be chosen from when users select template name as the source
=> [LG-Vscode-Extension]modify the LG live debug panel

packages/LUIS/test/luis.cli.specs.suite/with-add-verb.spec.json, packages/MSBot/src/msbot.ts, packages/MSBot/test/msbot.command.test.suite.js
=> Adding deprecation message and fixing test

packages/QnAMaker/bin/qnamaker.js
=> Replacing read-text-file with fs-extra in qnamaker.js

packages/LGvscodeExt/resources/lgPreviewTemplate.html
Fixes #
- Add restore states in monaco editors of reset button
-
-
=> [VS Code Extension]

packages/LGvscodeExt/resources/lgPreviewTemplate.html
Fixes #
- Before generate any result, click reset will cause an monaco editor undefined error. 
-
-
=> [Vscode Extenxion]fix a bug of output monaco editor undefined

packages/LGvscodeExt/resources/lgPreviewTemplate.html
Fixes #
- webview support of  light, dark and high contrast themes
- now the output monaco editor will initialize first before evaluating result
=> [vscode extension]add support for themes: light, dark and high contrast

packages/Chatdown/bin/chatdown.js
=> Fix spelling error around deprectated -> deprecated

package-lock.json, packages/LGvscodeExt/package-lock.json, packages/LGvscodeExt/package.json, packages/LGvscodeExt/src/providers/debugPanel.ts
Fixes #
- Now in the LG debug tool, generating results is using expandTemplate to generate result in order
to avoid duplicate text.
- botbuilder-lg package version now is changed to 4.6.0
- fix bugs
=> [LG vscode extension] change the mechanism of generating results 

packages/Ludown/lib/parseFileContents.js, packages/Ludown/test/ludown.roleTests.test.suite.js
=> Fixing pattern any entities issue #1225

packages/Ludown/lib/parseFileContents.js, packages/Ludown/test/ludown.roleTests.test.suite.js
=> Ludown pattern any

packages/Ludown/lib/ludown.js
=> [Ludown] Fix for #1226. Update availability now via stdout

packages/Ludown/docs/commands.md, packages/Ludown/docs/refresh-command.md, packages/Ludown/lib/ludown-refresh.js, packages/Ludown/lib/toLU-helpers.js, packages/Ludown/lib/toLU.js, packages/Ludown/test/ludown.examples.test.suite.js, packages/Ludown/test/testcases/all.json, packages/Ludown/test/testcases/all_qna.json, packages/Ludown/test/testcases/qna-alterations_Alterations.json, packages/Ludown/test/verified/luis_sorted.lu, packages/Ludown/test/verified/qna_a_sorted.lu, packages/Ludown/test/verified/qna_sorted.lu, packages/Ludown/test/verified/sorted.lu
Fixes #1228 
- Added a -r/ --sort option to ludown refresh that would sort LUIS/ QnA/ QnA Alteration models
- Verified existing tests pass
- Added new tests.
=> [Ludown] Add ability to sort model contents with ludown refresh

packages/DialogSchema/src/dialogSchemaLib.ts
formatting output in consisten way that causes errors/warnings to be collected in the errors pane of Visual studio.
=> change output so errors/warnings show in vs

packages/Ludown/lib/parseFileContents.js, packages/Ludown/test/ludown.roleTests.test.suite.js
Fixes #1250 
- Added new tests
=> [Ludown] Inline and explicit role definitions are handled correctly

packages/Ludown/docs/lu-file-format.md, packages/Ludown/lib/enums/luisbuiltintypes.js, packages/Ludown/lib/ludown-parse-ToLuis.js
Fixes #1258 
Verified existing tests pass
=> [Ludown] Update prebuilt entities list with the latest from LUIS

packages/Ludown/test/ludown.va.skills.test.suite.js, packages/Ludown/test/testcases/Skills/Calendar/Calendar.lu, packages/Ludown/test/testcases/Skills/Calendar/General.lu, packages/Ludown/test/testcases/Skills/Email/Email.lu, packages/Ludown/test/testcases/Skills/Email/General.lu, packages/Ludown/test/testcases/Skills/Todo/General.lu, packages/Ludown/test/testcases/Skills/Todo/ToDo.lu, packages/Ludown/test/verified/Skills/Calendar.json, packages/Ludown/test/verified/Skills/Email.json, packages/Ludown/test/verified/Skills/ToDo.json
Added core VA Skills as tests to ludown test suite
=> Adding tests for VA skills

packages/Ludown/docs/lu-file-format.md
Doc only change - update lu file format document for better content organization and flow.
=> [Ludown] Update lu file format doc

README.md
This removes a duplicate sentence in the intro of the README.
=> Remove duplicate line in README

packages/LUIS/bin/luis.js
Fixes #1220
Updating code to call a renamed swagger API.
=> Fix listUserLuisAccounts

packages/Ludown/lib/parseFileContents.js, packages/Ludown/test/ludown.parsefile.test.suite.js, packages/Ludown/test/verified/11.json, packages/Ludown/test/verified/7.json, packages/Ludown/test/verified/9.json, packages/Ludown/test/verified/9a.json, packages/Ludown/test/verified/all.json, packages/Ludown/test/verified/collate_refresh.lu, packages/Ludown/test/verified/collated-luis.json, packages/Ludown/test/verified/collated-luis_LUISBatchTest.json, packages/Ludown/test/verified/ref6.json, packages/Ludown/test/verified/ref8.json, packages/Ludown/test/verified/root2_luis.json, packages/Ludown/test/verified/root_luis.json
- Address ludown automatically adding pattern as an utterance
- Addresses a regression with prebuilt entity references in patterns.
- Updated existing tests
- Added new tests.
=> Fixes to ludown

packages/Ludown/lib/ludown.js, packages/Ludown/test/ludown.cli.test.suite.js
Fixes microsoft/botframework-cli#130
=> Fix for BF-CLI #130

packages/LUISGen/src/Program.cs
=> LuisGen deprecation message

packages/LGvscodeExt/syntaxes/lg.tmLanguage.json
Fixes #
- token rule for 
structure lg body
- structure-name
- expression
- property
- value
=> Add token rule and color for structure lg in lg-vsc-ext

README.md
Notice regarding new BF CLI, and sunset path for legacy tools with redirect to new tool
=> Scheyal patch 1

packages/LGvscodeExt/package.json, packages/LGvscodeExt/src/providers/diagnostics.ts
=> add configuration for diagnostic level of unknown functions in LG

packages/LGvscodeExt/package.json, packages/LGvscodeExt/src/providers/diagnostics.ts
=> [vscode extension] support user setting of custum function list 

packages/Dispatch/readme.md
Fixes #
Add best practice to directly adding utterances to Dispatch to improve Dispatch intent classification
=> Add best practice to directly adding utterances to Dispatch to improve Dispatch intent classication

packages/LUISGen/readme.md
=> deprecated message to luisgen tool

packages/QnAMaker/readme.md
=> added deprecation message to qnamaker tool

packages/Ludown/README.MD
=> Added legacy message for LuDown

packages/MSBot/README.md
=> added legacy tool message for MSBot

packages/Chatdown/readme.md
=> Add legacy message to Chatdown

packages/LUISGen/src/Program.cs
=> Switch deprecation message to Console.WriteLine

packages/LGvscodeExt/README.md, packages/LGvscodeExt/src/providers/diagnostics.ts
=> fix missing error messages and modify the documentation

packages/QnAMaker/bin/qnamaker.js, packages/QnAMaker/package.json
=> Revert breaking deprecation message

packages/Dispatch/readme.md
Fixes #
https://github.com/microsoft/botbuilder-tools/issues/1403
=> Added FAQ doc

packages/Dispatch/package.json
=> upversion for next update (as needed)

packages/Dispatch/readme.md
=> Added deprecation date.

build/PublishToCoveralls.ps1
Fixes #minor
Update PublishToCoveralls.ps1 to match the latest version in the botbuilder-dotnet repo.
Reference: https://github.com/microsoft/botbuilder-dotnet/pull/6439
=> Update PublishToCoveralls.ps1 in tools
